<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('bookings', function (Blueprint $table) {
            /*
            |--------------------------------------------------------------------------
            | Points Redemption
            |--------------------------------------------------------------------------
            */

            // Number of points redeemed for this booking.
            $table->unsignedBigInteger('points_redeemed')
                ->default(0)
                ->after('total_amount');

            // Monetary discount generated by redeemed points.
            $table->decimal('points_discount', 12, 2)
                ->default(0)
                ->after('points_redeemed');

            // Final amount payable after points discount.
            // Nullable keeps existing bookings compatible.
            $table->decimal('payable_amount', 12, 2)
                ->nullable()
                ->after('points_discount');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('bookings', function (Blueprint $table) {
            $table->dropColumn([
                'points_redeemed',
                'points_discount',
                'payable_amount',
            ]);
        });
    }
};